export const ADD_BET = 'ADD_BET';
export const GET_STAKE = 'GET_STAKE';
export const GET_RETURN = 'GET_RETURN';
//DETAILS FOR THE HOMEPAGE, THUMBNAIL, TEAMS ETC
export const GET_GAME = 'GET_GAME';
export const REMOVE_BET = 'REMOVE_BET';
export const REMOVE_ALL = 'REMOVE_ALL';
export const GET_TOTAL = 'GET_TOTAL';
//FULL DETAILS OF THE GAME, INCLUDING ODDS
export const GET_MATCH_DETAILS_REQUEST = 'GET_MATCH_DETAILS_REQUEST';
export const GET_MATCH_DETAILS_SUCCESS = 'GET_MATCH_DETAILS_SUCCESS';
export const GET_MATCH_DETAILS_FAILURE = 'GET_MATCH_DETAILS_FAILURE';
export const GET_UPCOMING = 'GET_UPCOMING';
export const GET_NEWS_STORIES = 'GET_NEWS_STORIES';
export const PLACE_BET = 'PLACE_BET';