// export const ADD_BET = 'ADD_BET';
// export const FETCH_STAKE = 'FETCH_STAKE';
// export const FETCH_RETURN = 'FETCH_RETURN';
// //DETAILS FOR THE HOMEPAGE, THUMBNAIL, TEAMS ETC
// export const FETCH_GAME = 'FETCH_GAME';
// export const REMOVE_BET = 'REMOVE_BET';
// export const REMOVE_ALL = 'REMOVE_ALL';
// export const FETCH_TOTAL = 'FETCH_TOTAL';
// //FULL DETAILS OF THE GAME, INCLUDING ODDS
// export const FETCH_MATCH_DETAILS_REQUEST = 'FETCH_MATCH_DETAILS_REQUEST';
// export const FETCH_MATCH_DETAILS_SUCCESS = 'FETCH_MATCH_DETAILS_SUCCESS';
// export const FETCH_MATCH_DETAILS_FAILURE = 'FETCH_MATCH_DETAILS_FAILURE';
// export const FETCH_UPCOMING = 'FETCH_UPCOMING';
// export const FETCH_NEWS_STORIES = 'FETCH_NEWS_STORIES';
// export const PLACE_BET = 'PLACE_BET';

export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';
export const FETCH_HOME_DATA_REQUEST = 'FETCH_HOME_DATA_REQUEST';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';