export const FETCH_HOME_DATA_FAILURE = "FETCH_HOME_DATA_FAILURE";
export const FETCH_HOME_DATA_REQUEST = "FETCH_HOME_DATA_REQUEST";
export const FETCH_HOME_DATA_SUCCESS = "FETCH_HOME_DATA_SUCCESS";

export const FETCH_GAME_DATA_FAILURE = "FETCH_GAME_DATA_FAILURE";
export const FETCH_GAME_DATA_REQUEST = "FETCH_GAME_DATA_REQUEST";
export const FETCH_GAME_DATA_SUCCESS = "FETCH_GAME_DATA_SUCCESS";

export const FETCH_BETSLIP_DATA_FAILURE = 'FETCH_BETSLIP_DATA_FAILURE';
export const FETCH_BETSLIP_DATA_REQUEST = 'FETCH_BETSLIP_DATA_REQUEST';
export const FETCH_BETSLIP_DATA_SUCCESS = 'FETCH_BETSLIP_DATA_SUCCESS';

export const POST_BETSLIP_DATA_FAILURE = "POST_BETSLIP_DATA_FAILURE";
export const POST_BETSLIP_DATA_REQUEST = "POST_BETSLIP_DATA_REQUEST";
export const POST_BETSLIP_DATA_SUCCESS = "POST_BETSLIP_DATA_SUCCESS"

export const FETCH_ACCOUNT_DATA_FAILURE = "FETCH_ACCOUNT_DATA_FAILURE";
export const FETCH_ACCOUNT_DATA_REQUEST = "FETCH_ACCOUNT_DATA_REQUEST";
export const FETCH_ACCOUNT_DATA_SUCCESS = "FETCH_ACCOUNT_DATA_SUCCESS";
export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const FETCH_RESULT_DATA_FAILURE = "FETCH_RESULT_DATA_FAILURE";
export const FETCH_RESULT_DATA_REQUEST = "FETCH_RESULT_DATA_REQUEST";
export const FETCH_RESULT_DATA_SUCCESS = "FETCH_RESULT_DATA_SUCCESS";

export const INSERT_STAKE = 'INSERT_STAKE';
export const CREATE_BET = 'CREATE_BET';
export const REMOVE_ALL = 'REMOVE_ALL';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const PLACE_BETS = 'PLACE_BETS';
export const REMOVE_BET = 'REMOVE_BET';
